Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,10 +23,25 @@ jobs:
             if [[ "icon" != "$dir" ]] ; then
               if [ ! -f "$dir/Dockerfiles/Dockerfile" ] ; then
                 echo "ERROR: $dir/Dockerfiles/Dockerfile does not exist"
+                exit 1
               fi
               if [ ! -f "$dir/$dir.attrs" ] ; then
                 echo "ERROR: $dir/$dir.attrs does not exist"
+                exit 1
               fi
+              if [ ! -f "$dir/$dir.json" ] ; then
+                echo "ERROR: $dir/$dir.json does not exist"
+                exit 1
+              fi
+              if [ ! -f "$dir/$dir.py" ] ; then
+                echo "ERROR: $dir/$dir.py does not exist"
+                exit 1
+              fi
+              if [ ! -f "$dir/$dir.states" ] ; then
+                echo "ERROR: $dir/$dir.states does not exist"
+                exit 1
+              fi
+              echo "All necessary files exist for widget $dir"
             fi
           done
           
